# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      semver-major-days: 7
      semver-minor-days: 1
      semver-patch-days: 1
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      aws-cdk:
        patterns:
          - "aws-cdk-lib"
          - "aws-cdk"
          - "@aws-cdk/*"
          - "constructs"
        update-types:
          - "minor"
          - "patch"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
        update-types:
          - "minor"
          - "patch"
      types:
        dependency-type: "development"
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
